// <auto-generated />
using System;
using DisneyApi.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DisneyApi.AccessData.Migrations
{
    [DbContext(typeof(DisneyApiContext))]
    partial class DisneyApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DisneyApi.Domain.Entities.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Age = 93,
                            History = "Mickey Mouse is a cartoon character created in 1928 by Walt Disney, and is the mascot of The Walt Disney Company. An anthropomorphic mouse who typically wears red shorts, large yellow shoes, and white gloves, Mickey is one of the world's most recognizable fictional characters",
                            Image = "Image here!",
                            Name = "Mickey Mouse",
                            Weight = 10
                        },
                        new
                        {
                            CharacterId = 2,
                            Age = 78,
                            History = "Donald duck is an animated character created by Walt Disney as a foil to Mickey Mouse.[15] Making his screen debut in The Wise Little Hen on June 9, 1934, Donald is characterized as a pompous, showboating duck wearing a sailor suit, cap and a bow tie",
                            Image = "Image here!",
                            Name = "Donald Duck",
                            Weight = 20
                        },
                        new
                        {
                            CharacterId = 3,
                            Age = 14,
                            History = "Snow White is the titular character and heroine of Disney's first animated feature-length film Snow White and the Seven Dwarfs. She is a young Princess; the Fairest of Them All who, in her innocence, cannot see any of the evil in the world",
                            Image = "Image here!",
                            Name = "Snow White",
                            Weight = 50
                        },
                        new
                        {
                            CharacterId = 4,
                            Age = 16,
                            History = "Mulan is the protagonist of Disney's 1998 animated feature film of the same name and its 2004 direct-to-video sequel. Mulan is the eighth official Disney Princess and first heroine in the line-up who is not actually royalty through either birth or marriage",
                            Image = "Image here!",
                            Name = "Mulan",
                            Weight = 55
                        },
                        new
                        {
                            CharacterId = 5,
                            Age = 89,
                            History = "Goofy is an animated character that first appeared in 1932's Mickey's Revue.He  is predominately known for his slapstick style of comedy, and regularly appears alongside his best friends Mickey Mouse and Donald Duck",
                            Image = "Image here!",
                            Name = "Goofy",
                            Weight = 70
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.CharacterMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterMovie");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CharacterId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CharacterId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            CharacterId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            CharacterId = 1
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Image = "Image here!",
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 2,
                            Image = "Image here!",
                            Name = "animation"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Qualification")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CreationDate = new DateTime(2004, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            Image = "Image here!",
                            Qualification = 1,
                            Title = "Mickey, Donald, Goofy: The Three Musketeers"
                        },
                        new
                        {
                            MovieId = 2,
                            CreationDate = new DateTime(1998, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Image = "Image here!",
                            Qualification = 2,
                            Title = "Mulan"
                        },
                        new
                        {
                            MovieId = 3,
                            CreationDate = new DateTime(1929, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Image = "Image here!",
                            Qualification = 3,
                            Title = "The Karnival Kid"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Admin Role",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "User Role",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "TestAdmin@disney.com",
                            Password = "12345678",
                            RoleId = 1,
                            Username = "TestAdmin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "TestUser@disney.com",
                            Password = "12345678",
                            RoleId = 2,
                            Username = "TestUser"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.CharacterMovie", b =>
                {
                    b.HasOne("DisneyApi.Domain.Entities.Character", "Character")
                        .WithMany("CharacterMovie")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisneyApi.Domain.Entities.Movie", "Movie")
                        .WithMany("CharacterMovie")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Movie", b =>
                {
                    b.HasOne("DisneyApi.Domain.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.User", b =>
                {
                    b.HasOne("DisneyApi.Domain.Entities.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Character", b =>
                {
                    b.Navigation("CharacterMovie");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Movie", b =>
                {
                    b.Navigation("CharacterMovie");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Role", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
